# Generated by Django 3.1.4 on 2021-01-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushtra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='schedule',
            field=models.JSONField(default={}),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
